### ISSUE TITLE
Adding tests for the developed smart contracts

### ISSUE THREAD

**Issue by balajipachai** [willitscale/learning-solidity#40]
Hi,

I am suggesting to add test cases for all the smart contracts in place.
I can take this up too, after documenting smart contracts.

Thanks,
Balaji

**Comment by willitscale** [comment]
These are tutorials and not intended for production use so tests are a bit useless.

**Comment by balajipachai** [comment]
Yes, agreed, what if someone wants to implement these tutorials and are confused like:

-  how to create smart contract instances?

- how to invoke the different functions?

Let me know what you think about this.

**Comment by willitscale** [comment]
Testing is covered in a number of tutorials, a good example would be tutorial 26 https://github.com/willitscale/learning-solidity/tree/master/tutorial-26

Writing a test for a hello world isn't going to help a noice developer and a lot of people picking up these tutorials aren't seasoned engineers so throwing testing concepts at them could be overwhelming and confusing.

The functions are easy enough to invoke via tools like Remix and I also show how to interact with functions using ganache+truffle, metamask and web3j. Granted I've not covered web3, but the idea was to be as simple as possible with minimal material to absorb after each tutorial rather than a whole project per tutorial with a full suite of unit and e2e tests.

I'm not trying to dash your eager suggestions and really appreciate the input, but I want to keep the tutorials as easy as possible to follow.

Thanks,
James

**Comment by balajipachai** [comment]
No, problem. Keeping it as simple as possible, sounds good.
Thanks,
Balaji
